import os
from collections import OrderedDict
from typing import Any, Dict, List, Literal, Optional, Set, Union
import msgspec
from msgspec import Meta, defstruct
from typing_extensions import Annotated
from msgflow.utils.common import type_mapping


class StructRebuilder:
    """Rebuild msgspec.Struct from a JSON-schema."""
    
    def __init__(self):
        self.reconstructed_classes = OrderedDict()
    
    @classmethod
    def reconstruct_from_schema(cls, schema: Dict[str, Any]) -> Dict[str, type]:
        """
        Rebuild all Struct classes defined in the schema.

        Args:
            schema: The JSON schema generated by msgspec

        Returns:
            Dict mapping class names to the reconstructed classes
        """
        self = cls() # Temp instance
        if "$defs" not in schema:
            raise ValueError("Schema must contain definitions in `$defs`")

        definitions = schema["$defs"]

        # First, we identify the dependency order
        dependency_order = self._get_dependency_order(definitions)

        # We rebuild the classes in the correct order
        for class_name in dependency_order:
            class_def = definitions[class_name]
            self._reconstruct_class(class_name, class_def, definitions)

        main_struct = self.reconstructed_classes.popitem(last=True)[1]
        return main_struct

    def _get_dependency_order(self, definitions: Dict[str, Any]) -> List[str]:
        """ Determines the construction order of classes based on dependencies."""
        dependencies = {}
        
        # Map dependencies for each class
        for class_name, class_def in definitions.items():
            deps = set()
            self._find_dependencies(class_def, deps, definitions.keys())
            dependencies[class_name] = deps
        
        # Sort topologically
        ordered = []
        remaining = set(definitions.keys())
        
        while remaining:
            # Find classes without unresolved dependencies
            ready = [name for name in remaining 
                    if dependencies[name].issubset(set(ordered))]
            
            if not ready: # Circular dependency - uses alphabetical order as fallback                
                ready = [min(remaining)]
            
            for name in ready:
                ordered.append(name)
                remaining.remove(name)
        
        return ordered
    
    def _find_dependencies(self, definition: Dict[str, Any], deps: Set[str], available_classes: Set[str]):
        """Recursively finds all dependencies of a definition."""
        if isinstance(definition, dict):
            # Check direct deps
            if "$ref" in definition:
                ref_name = definition["$ref"].split("/")[-1]
                if ref_name in available_classes:
                    deps.add(ref_name)
            
            # Check in properties
            if "properties" in definition:
                for prop_def in definition["properties"].values():
                    self._find_dependencies(prop_def, deps, available_classes)
            
            # Checks on anyOf (for optional fields)
            if "anyOf" in definition:
                for item in definition["anyOf"]:
                    self._find_dependencies(item, deps, available_classes)
            
            # Checks on items (for arrays)
            if "items" in definition:
                self._find_dependencies(definition["items"], deps, available_classes)
    
    def _reconstruct_class(self, class_name: str, class_def: Dict[str, Any], all_definitions: Dict[str, Any]):
        """Rebuild single class."""
        if class_name in self.reconstructed_classes:
            return self.reconstructed_classes[class_name]
        
        properties = class_def.get("properties", {})
        required_fields = set(class_def.get("required", []))
        
        fields = []
        
        for field_name, field_def in properties.items():
            field_type = self._resolve_field_type(field_def, all_definitions)
                        
            if field_name in required_fields: # Checks if the field is required
                fields.append((field_name, field_type)) # Required field - type can be annotated
            else:
                fields.append((field_name, field_type, None)) # Optional field - can be annotated
        
        reconstructed_class = defstruct(
            class_name,
            fields,
            kw_only=True, # default
            module=__name__
        )
        
        self.reconstructed_classes[class_name] = reconstructed_class
        return reconstructed_class
    
    def _resolve_field_type(self, field_def: Dict[str, Any], all_definitions: Dict[str, Any]):
        """Resolves the type of a field based on the schema definition."""        
        if "anyOf" in field_def: # If it has anyOf, treat it as Union (optional field)
            types = []
            description = None
            
            for option in field_def["anyOf"]:
                if option.get("type") == "null":
                    continue  # Skip null, it will be treated as Optional
                                
                if "description" in option: # Capture description if exists
                    description = option["description"]
                
                option_type = self._resolve_single_type(option, all_definitions)
                if option_type and option_type != type(None):
                    types.append(option_type)
            
            if len(types) == 1:
                base_type = types[0]
                if description:
                    annotated_type = Annotated[base_type, Meta(description=description)]
                    return Optional[annotated_type]
                else:
                    return Optional[base_type]
            elif len(types) > 1:
                if description:
                    union_type = Union[tuple(types)]
                    annotated_type = Annotated[union_type, Meta(description=description)]
                    return Optional[annotated_type]
                else:
                    return Optional[Union[tuple(types)]]
            else:
                return Optional[str]  # Fallback
        
        return self._resolve_single_type(field_def, all_definitions)
    
    def _resolve_single_type(self, type_def: Dict[str, Any], all_definitions: Dict[str, Any]):
        """Resolves a unique type based on the definition."""
        if "$ref" in type_def: # Ref to other struct
            ref_name = type_def["$ref"].split("/")[-1]
            if ref_name in self.reconstructed_classes:
                return self.reconstructed_classes[ref_name]
            else:
                # Class not yet constructed, returns by name
                # This should be resolved by dependency order
                return ref_name

        if "enum" in type_def: # Enum/Literal
            enum_values = type_def["enum"]
            description = type_def.get("description")
            
            # If all values ​​are of the same type, use Literal
            if len(enum_values) > 0:
                if len(enum_values) == 1:
                    literal_type = Literal[enum_values[0]]
                else:
                    literal_type = Literal[tuple(enum_values)]
                                
                if description: # If has description, use with Annotated
                    return Annotated[literal_type, Meta(description=description)]
                else:
                    return literal_type

        if "type" in type_def: # Built-in type
            type_name = type_def["type"]
            
            if type_name == "array":
                if "items" in type_def: # Array with specific items
                    item_type = self._resolve_single_type(type_def["items"], all_definitions)
                    return List[item_type]
                else:
                    return List[Any]
            
            return type_mapping.get(type_name, str)
        
        return str  # Fallback

def export_to_toml(obj, filepath):
    with open(filepath, "wb") as f:
        f.write(msgspec.toml.encode(obj))    

def export_to_json(obj, filepath, indent=4):
    with open(filepath, "wb") as f:
        obj_b = msgspec.json.encode(obj)
        formatted_obj_b = msgspec.json.format(obj_b, indent=indent)
        f.write(formatted_obj_b)

def save(obj: object, f: Union[str, os.PathLike], format: Optional[Literal["toml", "json"]] = "toml"):
    """
    Save a Python object to a file in either TOML or JSON format.

    Args:
        data: Saved object
        filepath: A string or os.PathLike object containing a file name
        format: The format to save the file in. Can be "toml" or "json", defaults to "toml"

    Raises:
        ValueError: If the provided format is not "toml" or "json"
        FileNotFoundError: If the directory of the provided filepath does not exist

    !!! example
        ``` python
        data = {"name": "Satoshi", "age": 42}
        save(data, "output", format="toml")
        save(data, "output", format="json")
        ```
    """
    directory = os.path.dirname(f)
    if directory and not os.path.exists(directory):
        raise FileNotFoundError(f"The directory `{directory}` does not exist")
    
    if format == "toml":
        export_to_toml(obj, f)
    elif format == "json":
        export_to_json(obj, f)
    else:
        raise ValueError(f"Unsupported format: `{format}`. Use `toml` or `json`")

def read_json(filepath):
    with open(filepath, "rb") as f:
        return msgspec.json.decode(f.read())

def read_toml(filepath):
    with open(filepath, "rb") as f:
        return msgspec.toml.decode(f.read())

def load(f: Union[str, os.PathLike]) -> Any:
    """
    Load data from a file in either JSON or TOML format.

    Args:
        f: A string or os.PathLike object containing a file name

    Returns:
        The Python object loaded from the file

    Raises:
        FileNotFoundError: If the file does not exist
        ValueError: If the file extension is not ".json" or ".toml"

    !!! example
        ``` python
        data = load("data.toml")
        data = load("data.json")
        ```        
    """
    if not os.path.exists(f):
        raise FileNotFoundError(f"The file `{f}` does not exist.")

    if f.endswith(".json"):
        return read_json(f)
    elif f.endswith(".toml"):
        return read_toml(f)
    else:
        raise ValueError(f"Unsupported file extension: `{f}`. Use `.json` or `.toml`")

def struct_to_dict(obj):
    """
    Recursively converts a msgspec.Struct object to a pure Python dictionary
    """
    if isinstance(obj, msgspec.Struct):
        # Convert the struct to a dictionary and recursively process each value
        return {k: struct_to_dict(v) for k, v in msgspec.structs.asdict(obj).items()}
    elif isinstance(obj, list):
        # Convert each item in the list recursively
        return [struct_to_dict(item) for item in obj]
    elif isinstance(obj, dict):
        # If it is a dictionary, recursively convert its values
        return {k: struct_to_dict(v) for k, v in obj.items()}
    else: # Returns the value as is for simple types
        return obj
